---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: api
  strategy:
    type: Recreate
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/component: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args: ['serve', '--bind', '0.0.0.0:5000']
          env:
            - name: BRIGHTSKY_DATABASE_URL
              value: postgres://brightsky:brightsky@postgres.{{ .Release.Namespace }}.svc.cluster.local:5432
            - name: TZ
              value: "{{ .Values.TZ }}"
          ports:
            - name: http
              containerPort: 5000
          startupProbe:
            httpGet:
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            httpGet:
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
            successThreshold: 1
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits: {}
