apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: brightsky
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.ingressHost }}`)
      kind: Rule
      services:
        - name: api
          port: 5000
