---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      serviceAccountName: traefik
      containers:
        - name: traefik
          image: "traefik:v3.0.0"
          args:
            - "--global.checknewversion=false"
            - "--global.sendanonymoususage=false"
            - "--certificatesresolvers.dns.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
            - "--certificatesresolvers.dns.acme.dnschallenge=true"
            - "--certificatesresolvers.dns.acme.dnschallenge.provider=gcloud"
            - "--certificatesresolvers.dns.acme.email=jan@jansauer.de"
            - "--certificatesresolvers.dns.acme.keytype=EC384"
            - "--certificatesresolvers.dns.acme.storage=/acme/dns.json"
            - "--entryPoints.websecure.address=:8443/tcp"
            - "--entrypoints.websecure.http.tls.certresolver=dns"
            - "--entrypoints.websecure.http.tls.domains[0].main=jansauer.dev"
            - "--entrypoints.websecure.http.tls.domains[0].sans=*.jansauer.dev"
            - "--entryPoints.web.address=:8080/tcp"
            - "--entryPoints.web.http.redirections.entrypoint.scheme=https"
            - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
            - "--entryPoints.traefik.address=:9000/tcp"
            - "--providers.kubernetescrd"
            - "--api.insecure"
            - "--metrics.prometheus"
            - "--ping"
            - "--log.level=DEBUG"
          env:
            - name: GCE_SERVICE_ACCOUNT_FILE
              value: /acme/personal-358315-6c8ec91782b3.json
          volumeMounts:
            - name: acme
              mountPath: /acme
            - name: tmp
              mountPath: /tmp
          ports:
            - name: websecure
              containerPort: 8443
            - name: web
              containerPort: 8080
            - name: traefik
              containerPort: 9000
          readinessProbe:
            httpGet:
              path: /ping
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /ping
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
            successThreshold: 1
          securityContext:
            capabilities:
              drop: [ALL]
            readOnlyRootFilesystem: true
            runAsGroup: 65532
            runAsNonRoot: true
            runAsUser: 65532
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "300m"
              memory: "150Mi"
      securityContext:
        fsGroup: 65532
      volumes:
        - name: acme
          hostPath:
            type: Directory
            path: {{ .Values.acmeStorageHostPath }}
        - name: tmp
          emptyDir: {}
