---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    version: {{ .Chart.Version }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: grafana
          image: 'grafana/grafana:10.1.10'
          env:
            - name: GF_SERVER_ROOT_URL
              value: "https://grafana.jansauer.de/"
            - name: GF_AUTH_DISABLE_LOGIN_FORM
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: "Admin"
            - name: GF_AUTH_BASIC_ENABLED
              value: "false"
            - name: GF_ANALYTICS_REPORTING_ENABLED
              value: "false"
            - name: GF_ANALYTICS_CHECK_FOR_UPDATES
              value: "false"
          volumeMounts:
            - name: data
              mountPath: /var/lib/grafana
            - name: tmp
              mountPath: /tmp
          ports:
            - name: http
              containerPort: 3000
          securityContext:
            capabilities:
              drop: [ ALL ]
              add:
                - NET_BIND_SERVICE
            readOnlyRootFilesystem: true
            runAsGroup: 472
            runAsUser: 472
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
            successThreshold: 1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
      securityContext:
        fsGroup: 472
      volumes:
        - name: data
          hostPath:
            type: Directory
            path: "{{ .Values.grafanaStorage.dataHostPath }}"
        - name: tmp
          emptyDir: {}
