apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  type: LoadBalancer
  selector:
    app: {{ template "fullname" . }}
  sessionAffinity: None
  ports:
    - name: websecure
      port: {{ .Values.traefikNetwork.websecurePort }}
      targetPort: websecure
    - name: web
      port: {{ .Values.traefikNetwork.webPort }}
      targetPort: web
    - name: traefik
      port: 9002
      targetPort: 9000
