---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
  strategy:
    type: Recreate
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/component: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args: ['--migrate', 'work']
          env:
            - name: BRIGHTSKY_DATABASE_URL
              value: "postgres://brightsky:brightsky@postgres.{{ .Release.Namespace }}.svc.cluster.local:5432"
            - name: BRIGHTSKY_REDIS_URL
              value: "redis://valkey.{{ .Release.Namespace }}.svc.cluster.local:6379"
            - name: BRIGHTSKY_MIN_DATE
              value: "{{ .Values.minDate }}"
            - name: BRIGHTSKY_POLLING_CRONTAB_MINUTE
              value: "{{ .Values.pollingInterval }}"
            - name: TZ
              value: "{{ .Values.TZ }}"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits: {}
